### ISSUE TITLE
qvm-create-windows-qube.sh runs in dom0 and passes dom0 $HOME (which is /home/admin) to windows-mgmt domU, where path does not exist.

### ISSUE THREAD

**Issue by brendanhoar** [crazyqube/qvm-create-windows-qube#3]
Based on master branch today today (8/24/2019), the value of dom0's $HOME variable should not be passed into a domU if you want to find files in /home/user (particularly, the windows ISO file).

**Comment by brendanhoar** [comment]
I have manually replaced $HOME with /home/user in the script and it is now installing windows in the new VM...

**Comment by crazyqube** [comment]
Thanks for the patch. I set my Dom0 username to "user" during installation and assumed the fact that the DomUs also adopted that username was because it would get set to whatever the username of my Dom0 was set to be; hence why this wasn't an issue for me. I now know that was an incorrect assumption. Thanks again.
